apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gsd47fgm5-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:fe09026f8f3bf93be4c86819387ed93aecb4980a@sha256:aa503cafb308786c3d30f29b19aca8f12fc88805aafe0b1180c5f604c8b3f5cc
          name: container-image
