apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gsd47fgm5-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/gsd47fgm5-nodejs-gitops